import type { Appearance } from "./qr";

export const destinations = [
  {
    id: "website",
    name: "Website URL",
    mark: "↗",
    color: "#a885f1",
    field: "Website URL",
    placeholder: "https://your-website.com",
    description: "A website, landing page or any public link.",
  },
  {
    id: "instagram",
    name: "Instagram",
    mark: "◎",
    color: "#e586bb",
    field: "Instagram profile or post URL",
    placeholder: "https://www.instagram.com/yourname/",
    description: "Your profile, portfolio, post or reel.",
  },
  {
    id: "reviews",
    name: "Google reviews",
    mark: "G",
    color: "#80c5a4",
    field: "Google review link",
    placeholder: "https://g.page/r/your-business/review",
    description: "A direct link to your business review page.",
  },
  {
    id: "wifi",
    name: "Wi-Fi",
    mark: "⌁",
    color: "#7baee7",
    field: "Network name",
    placeholder: "Your Wi-Fi network",
    description: "Let guests join your network with a scan.",
  },
  {
    id: "pdf",
    name: "PDF document",
    mark: "PDF",
    color: "#ed9b90",
    field: "Public PDF URL",
    placeholder: "https://your-website.com/document.pdf",
    description: "Share a PDF already hosted at a public URL.",
  },
  {
    id: "tiktok",
    name: "TikTok",
    mark: "♪",
    color: "#7acac6",
    field: "TikTok profile or video URL",
    placeholder: "https://www.tiktok.com/@yourname",
    description: "Send people to your creator profile or video.",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    mark: "in",
    color: "#77aafa",
    field: "LinkedIn profile or company URL",
    placeholder: "https://www.linkedin.com/in/yourname/",
    description: "Make professional connections in person.",
  },
  {
    id: "snapchat",
    name: "Snapchat",
    mark: "S",
    color: "#dfd273",
    field: "Snapchat public profile URL",
    placeholder: "https://www.snapchat.com/add/yourname",
    description: "Share your public profile with an ordinary QR.",
  },
  {
    id: "youtube",
    name: "YouTube",
    mark: "▶",
    color: "#ed898c",
    field: "YouTube channel or video URL",
    placeholder: "https://www.youtube.com/@yourchannel",
    description: "Connect viewers to your channel or video.",
  },
  {
    id: "spotify",
    name: "Spotify",
    mark: "≋",
    color: "#88c99c",
    field: "Spotify playlist or artist URL",
    placeholder: "https://open.spotify.com/playlist/…",
    description: "Share a song, album, playlist or artist page.",
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    mark: "◔",
    color: "#84c6a0",
    field: "WhatsApp chat or channel URL",
    placeholder: "https://wa.me/…",
    description: "Give people a direct route to your chat.",
  },
  {
    id: "facebook",
    name: "Facebook",
    mark: "f",
    color: "#85a8ed",
    field: "Facebook page, group or event URL",
    placeholder: "https://www.facebook.com/yourpage",
    description: "Bring people to a page, group or event.",
  },
  {
    id: "amazon",
    name: "Amazon",
    mark: "a",
    color: "#d7ae78",
    field: "Amazon product or storefront URL",
    placeholder: "https://www.amazon.com/…",
    description: "Share a product, storefront or wishlist.",
  },
  {
    id: "x",
    name: "X",
    mark: "𝕏",
    color: "#aaa7ba",
    field: "X profile or post URL",
    placeholder: "https://x.com/yourname",
    description: "Put your profile or a conversation within reach.",
  },
  {
    id: "maps",
    name: "Google Maps",
    mark: "⌖",
    color: "#99be8b",
    field: "Google Maps place or directions URL",
    placeholder: "https://maps.google.com/…",
    description: "Help people find your place or business.",
  },
  {
    id: "vcard",
    name: "Contact card",
    mark: "▣",
    color: "#e6a98d",
    field: "Full name",
    placeholder: "Your name",
    description: "Share a name, phone number and email address.",
  },
  {
    id: "menu",
    name: "Restaurant menu",
    mark: "♧",
    color: "#d5a779",
    field: "Menu URL",
    placeholder: "https://your-restaurant.com/menu",
    description: "Put your online menu on every table.",
  },
  {
    id: "forms",
    name: "Google Forms",
    mark: "▤",
    color: "#b093e0",
    field: "Public form URL",
    placeholder: "https://forms.gle/…",
    description: "Open a form, survey or registration page.",
  },
] as const;
export type DestinationId = (typeof destinations)[number]["id"];
export const featuredDestinations: DestinationId[] = [
  "website",
  "instagram",
  "linkedin",
  "tiktok",
  "youtube",
  "whatsapp",
  "snapchat",
  "facebook",
];
export type GeneratorMode = "custom" | "image" | "art";
export const templates: (Appearance & { name: string })[] = [
  {
    name: "Essential",
    foreground: "#202025",
    background: "#ffffff",
    style: "soft",
    quietZone: 4,
  },
  {
    name: "Violet",
    foreground: "#7028c9",
    background: "#ffffff",
    style: "soft",
    quietZone: 4,
  },
  {
    name: "Midnight dots",
    foreground: "#174767",
    background: "#ffffff",
    style: "dot",
    quietZone: 4,
  },
  {
    name: "Cherry",
    foreground: "#a32149",
    background: "#fff9f8",
    style: "soft",
    quietZone: 4,
  },
  {
    name: "Electric",
    foreground: "#511594",
    background: "#f3efff",
    style: "square",
    quietZone: 4,
  },
  {
    name: "Terracotta",
    foreground: "#843819",
    background: "#fff1df",
    style: "dot",
    quietZone: 4,
  },
  {
    name: "Pine",
    foreground: "#185347",
    background: "#ffffff",
    style: "soft",
    quietZone: 4,
  },
  {
    name: "Rose",
    foreground: "#813353",
    background: "#fff5f8",
    style: "square",
    quietZone: 4,
  },
  {
    name: "Cobalt",
    foreground: "#173c97",
    background: "#ffffff",
    style: "soft",
    quietZone: 4,
  },
  {
    name: "Espresso",
    foreground: "#594237",
    background: "#fff9ee",
    style: "dot",
    quietZone: 4,
  },
  {
    name: "Amber",
    foreground: "#854d08",
    background: "#fffdf3",
    style: "square",
    quietZone: 4,
  },
  {
    name: "Lagoon",
    foreground: "#174957",
    background: "#e8f9f4",
    style: "soft",
    quietZone: 4,
  },
  {
    name: "Orchid",
    foreground: "#9c227e",
    background: "#fff4fc",
    style: "soft",
    quietZone: 4,
  },
  {
    name: "Glacier",
    foreground: "#24585f",
    background: "#e7f9ff",
    style: "dot",
    quietZone: 4,
  },
  {
    name: "Graphite",
    foreground: "#303038",
    background: "#f2f2f6",
    style: "square",
    quietZone: 4,
  },
];
