/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 53393d2a9a1c0f0d061eeae4c3567440)
interface __BaseEnv_CloudflareEnv {
	API_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	QR_SERVICE: Fetcher /* qr-upgrade-service */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cloudflare/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
