import test from 'node:test';
import assert from 'node:assert/strict';
import Stripe from 'stripe';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {billingRequest} from '../workers/qr-service/billing.mjs';
import {billingAction,billingStatus,billingWebhook,billingReady,readBillingBody,type BillingConfig} from '../src/lib/server/billing';
import {signAccountToken} from '../src/lib/server/account';
const owner='a'.repeat(64),other='b'.repeat(64);
const c:BillingConfig={enabled:true,key:'sk_test_fixture',webhookSecret:'whsec_fixture',pro:'price_pro',brand:'price_brand',account:{clientId:'test',clientSecret:'test',secret:'s'.repeat(64),serviceUrl:'https://service.example',development:true}};
function db(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../workers/qr-service/migrations/0005_billing.sql',import.meta.url),'utf8'));const wrap=(sql:string,values:any[]=[])=>({bind:(...v:any[])=>wrap(sql,v),first:async()=>sqlite.prepare(sql).get(...values)||null});return {sqlite,DB:{prepare:wrap}};}
function req(path='/billing',method='GET',body?:unknown,user=owner){return new Request('https://service.example'+path,{method,headers:{'x-qr-user':user,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});}
function fixture(){const env=db();let creates=0;const sessions=new Map<string,any>();const subs:any[]=[];const s={prices:{retrieve:async(id:string)=>({id,active:true,livemode:false,type:'recurring',recurring:{interval:'month',interval_count:1,usage_type:'licensed'},billing_scheme:'per_unit',unit_amount:1200,currency:'usd'})},customers:{create:async()=>({id:'cus_fixture'}),retrieve:async()=>({id:'cus_fixture',livemode:false,metadata:{owner}})},subscriptions:{list:async()=>({data:subs,has_more:false})},checkout:{sessions:{create:async(p:any,o:any)=>{creates++;assert.equal(p.customer,'cus_fixture');assert.equal(p.line_items[0].quantity,1);assert.equal(p.success_url,'http://localhost:3040/billing?checkout=returned');assert.equal(p.cancel_url,'http://localhost:3040/billing?checkout=cancelled');const session=sessions.get(o.idempotencyKey)||{id:'cs_test_fixture',customer:'cus_fixture',livemode:false,mode:'subscription',status:'open',url:'https://checkout.stripe.com/c/pay/fixture'};sessions.set(o.idempotencyKey,session);return session;},retrieve:async()=>[...sessions.values()][0]}},billingPortal:{sessions:{create:async(p:any)=>{assert.equal(p.return_url,'http://localhost:3040/billing');return {url:'https://billing.stripe.com/p/session/fixture'};}}},webhooks:new Stripe('sk_test_fixture').webhooks};const fetcher:typeof fetch=async(input,init)=>billingRequest(new Request(input as string,init),env);return {env,s,subs,sessions,deps:{stripe:s as unknown as Stripe,fetch:fetcher},get creates(){return creates;}};}
async function browser(body:unknown={tier:'pro'},origin='http://localhost:3040'){const token=await signAccountToken({sub:owner,name:'Fixture',email:'fixture@example.com'},'session',c.account);return new Request('http://localhost:3040/api/billing/checkout',{method:'POST',headers:{origin,cookie:`qr-session=${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});}
test('disabled readiness and anonymous offers; bad configured prices and network fail closed',async()=>{const f=fixture();assert.equal(billingReady({...c,brand:c.pro}),false);const off=await billingStatus(req(),{...c,enabled:false},f.deps);assert.deepEqual(await off.json(),{configured:false,signedIn:false,plans:[],subscription:null,canManage:false});const on=await(await billingStatus(req(),c,f.deps)).json();assert.equal(on.plans[0].amount,1200);assert.equal(on.signedIn,false);f.s.prices.retrieve=async()=>{throw new Error('private');};assert.equal((await billingStatus(req(),c,f.deps)).status,503);f.env.sqlite.close();});
test('auth, same-origin, exact payload and bounded body gates',async()=>{const f=fixture();assert.equal((await billingAction(req(),'checkout',c,f.deps)).status,401);assert.equal((await billingAction(await browser({},'https://evil.example'),'checkout',c,f.deps)).status,403);for(const b of [{tier:'pro',customer:'cus_other'},{tier:'unknown'},[],null,{tier:'pro',x:'x'.repeat(1100)}])assert.equal((await billingAction(await browser(b),'checkout',c,f.deps)).status,400);assert.equal((await billingAction(await browser({customer:'cus_other'}),'portal',c,f.deps)).status,400);await assert.rejects(()=>readBillingBody(new Request('https://example.com',{method:'POST',body:'x'.repeat(1025)})));f.env.sqlite.close();});
test('unique immutable customer bindings and cross-owner isolation in real SQLite',async()=>{const env=db();assert.equal((await billingRequest(req('/billing/customer','PUT',{customerId:'cus_fixture',mode:'test'}),env)).status,200);assert.equal((await billingRequest(req('/billing/customer','PUT',{customerId:'cus_other',mode:'test'}),env)).status,409);assert.equal((await billingRequest(req('/billing/customer','PUT',{customerId:'cus_fixture',mode:'test'},other),env)).status,409);assert.equal((await(await billingRequest(req('/billing','GET',undefined,other),env)).json()).binding,null);env.sqlite.close();});
test('checkout serializes concurrent tiers, reuses open session, and current subscription goes to portal',async()=>{const f=fixture();const responses=await Promise.all([billingAction(await browser(),'checkout',c,f.deps),billingAction(await browser({tier:'brand'}),'checkout',c,f.deps)]);assert.ok(responses.some(r=>r.status===200));assert.equal(f.creates,1);const next=await billingAction(await browser({tier:'brand'}),'checkout',c,f.deps);assert.equal(next.status,200);assert.equal(f.creates,1);f.subs.push({customer:'cus_fixture',livemode:false,status:'past_due',cancel_at_period_end:false,items:{data:[{quantity:1,price:{id:'price_pro'},current_period_end:123}]}});const portal=await(await billingAction(await browser(),'checkout',c,f.deps)).json();assert.match(portal.url,/billing.stripe.com/);const status=await(await billingStatus(await browser(),c,f.deps)).json();assert.equal(status.subscription.status,'past_due');assert.equal(status.canManage,true);f.env.sqlite.close();});
test('ambiguous provider response preserves reservation and recovers same idempotency key',async()=>{const f=fixture(),original=f.s.checkout.sessions.create;let first=true;f.s.checkout.sessions.create=async(p,o)=>{const result=await original(p,o);if(first){first=false;throw new Error('Connection lost');}return result;};assert.equal((await billingAction(await browser(),'checkout',c,f.deps)).status,503);const before=f.env.sqlite.prepare('SELECT * FROM billing_customers').get()!;assert.ok(before.reservation);f.env.sqlite.prepare('UPDATE billing_customers SET lease_until=0').run();assert.equal((await billingAction(await browser({tier:'brand'}),'checkout',c,f.deps)).status,200);assert.equal(f.sessions.size,1);const after=f.env.sqlite.prepare('SELECT * FROM billing_customers').get()!;assert.equal(after.reservation,before.reservation);assert.equal(after.tier,'pro');f.env.sqlite.close();});
test('real SDK signatures reject tamper, expired replay, cross-mode and oversize; durable events deduplicate unordered delivery',async()=>{const f=fixture();await billingRequest(req('/billing/customer','PUT',{customerId:'cus_fixture',mode:'test'}),f.env);const sdk=new Stripe('sk_test_fixture');const make=(event:any,timestamp=Math.floor(Date.now()/1000),bad=false)=>{const payload=JSON.stringify(event);return new Request('https://qrupgrade.com/api/billing/webhook',{method:'POST',headers:{'stripe-signature':bad?'bad':sdk.webhooks.generateTestHeaderString({payload,secret:c.webhookSecret!,timestamp})},body:payload});};const event={id:'evt_fixture',type:'customer.subscription.updated',created:100,livemode:false,data:{object:{object:'subscription',id:'sub_fixture',customer:'cus_fixture'}}};assert.equal((await billingWebhook(make(event,1),c,f.deps)).status,400);assert.equal((await billingWebhook(make(event,undefined,true),c,f.deps)).status,400);assert.equal((await billingWebhook(make({...event,livemode:true}),c,f.deps)).status,400);assert.equal((await billingWebhook(make({...event,x:'a'.repeat(256*1024)}),c,f.deps)).status,400);for(const e of [event,event,{...event,id:'evt_older',created:50}])assert.equal((await billingWebhook(make(e),c,f.deps)).status,200);assert.equal(f.env.sqlite.prepare('SELECT COUNT(*) AS n FROM billing_events').get()!.n,2);assert.equal((await billingWebhook(make({...event,id:'evt_unknown',data:{object:{...event.data.object,customer:'cus_unknown'}}}),c,f.deps)).status,200);assert.equal(f.env.sqlite.prepare('SELECT COUNT(*) AS n FROM billing_events').get()!.n,2);const badDeps={...f.deps,fetch:async()=>{throw new Error('offline');}};assert.equal((await billingWebhook(make(event),c,badDeps)).status,503);f.env.sqlite.close();});
test('invalid configured prices, subscription overflow and untrusted hosted URLs fail unavailable',async()=>{const f=fixture();const price=f.s.prices.retrieve;for(const patch of [{active:false},{unit_amount:0},{currency:'USD!'},{livemode:true},{recurring:{interval:'week',interval_count:1,usage_type:'licensed'}},{billing_scheme:'tiered'}]){f.s.prices.retrieve=async(id)=>({...await price(id),...patch}) as any;assert.equal((await billingStatus(req(),c,f.deps)).status,503);}f.s.prices.retrieve=price;await billingAction(await browser(),'checkout',c,f.deps);const listing=f.s.subscriptions.list;f.s.subscriptions.list=async()=>({data:[],has_more:true});assert.equal((await billingStatus(await browser(),c,f.deps)).status,503);f.s.subscriptions.list=listing;f.s.billingPortal.sessions.create=async()=>({url:'https://billing.stripe.com.evil.example/pay'});assert.equal((await billingAction(await browser({}),'portal',c,f.deps)).status,503);f.env.sqlite.close();});
test('reservation replay retains exact create payload; stale ambiguity requires reconciliation',async()=>{const f=fixture(),create=f.s.checkout.sessions.create;let original='';f.s.checkout.sessions.create=async(p,o)=>{if(original)assert.equal(JSON.stringify(p),original);else original=JSON.stringify(p);await create(p,o);throw new Error('ambiguous');};await billingAction(await browser(),'checkout',c,f.deps);f.env.sqlite.prepare('UPDATE billing_customers SET lease_until=0').run();await billingAction(await browser({tier:'brand'}),'checkout',c,f.deps);assert.equal(f.creates,2);f.env.sqlite.prepare('UPDATE billing_customers SET lease_until=0,reserved_at=?').run(Math.floor(Date.now()/1000)-24*3600);assert.equal((await billingAction(await browser(),'checkout',c,f.deps)).status,503);assert.equal(f.creates,2);f.env.sqlite.close();});
