'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
type Status={configured:boolean;signedIn:boolean;user:{name:string;email:string}|null};
export default function AccountPanel(){
 const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const controller=new AbortController();fetch('/api/account',{cache:'no-store',signal:controller.signal}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(setStatus).catch(()=>{if(!controller.signal.aborted)setError('Your account could not be loaded. Please refresh to try again.');});if(new URLSearchParams(window.location.search).has('error'))setError('Sign-in could not be completed. Please try again and allow access to your verified Google email.');return()=>controller.abort();},[]);
 async function signOut(){setBusy(true);setError('');try{const r=await fetch('/api/account/logout',{method:'POST'});if(!r.ok)throw new Error();setStatus(s=>s?{...s,signedIn:false,user:null}:s);}catch{setError('Sign-out could not be completed. Please try again.');}finally{setBusy(false);}}
 return <main id="main" className="account-page"><nav><Link href="/">QR<span>UPGRADE</span></Link><Link href="/generator">Back to studio ↗</Link></nav><section className="account-card"><span className="account-eyebrow">YOUR QR UPGRADE ACCOUNT</span><h1>{status?.signedIn?'A space for your work.':'Keep your designs close.'}</h1><p className="account-intro">Create in the studio. Keep a local copy in this browser, or sign in to access private cloud storage.</p>{error&&<p className="account-error" role="alert">{error}</p>}{!status&&!error&&<p role="status">Loading your account…</p>}{status?.signedIn&&status.user?<div className="account-identity"><div className="account-avatar" aria-hidden="true">{status.user.name.slice(0,1).toUpperCase()}</div><div><strong>{status.user.name}</strong><p>{status.user.email}</p></div><button onClick={signOut} disabled={busy}>{busy?'Signing out…':'Sign out'}</button></div>:status?.configured?<a className="account-google" href="/api/account/login"><span aria-hidden="true">G</span>Continue with Google</a>:status?<div className="account-setup"><strong>Google sign-in is being set up.</strong><p>Cloud accounts are not available yet. You can create, save and reopen designs locally in the studio right now.</p></div>:null}<div className="account-local"><span aria-hidden="true">↗</span><div><h2>Your studio is always available.</h2><p>Local designs stay in this browser. Private cloud designs belong to your signed-in account.</p><Link href="/designs">On this device</Link> · <Link href="/cloud-designs">Cloud collection</Link></div></div></section><footer>Thoughtfully designed. Yours to make.</footer></main>;
}
