'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
type Progress={ready?:boolean;accepted:boolean;complete:boolean;cleanup:string};
export default function AccountDeletionPanel({signedIn,onAccepted}:{signedIn:boolean;onAccepted:()=>void}){
 const [progress,setProgress]=useState<Progress|null>(null),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch('/api/account/deletion',{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error();return r.json();}).then(data=>{setProgress(data);if(data.accepted)onAccepted();}).catch(()=>{});return()=>controller.abort();},[]); // Receipt lookup also recovers a lost acceptance response.
 async function status(){setBusy(true);setError('');try{const r=await fetch('/api/account/deletion',{cache:'no-store'}),data=await r.json();if(!r.ok)throw new Error(data.error);setProgress(data);if(data.accepted)onAccepted();}catch(e){setError(e instanceof Error?e.message:'Closure status could not be confirmed. Try again.');}finally{setBusy(false);}}
 async function action(verify:boolean){setBusy(true);setError('');try{const r=await fetch(verify?'/api/account/deletion/verify':'/api/account/deletion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm:true})}),data=await r.json();if(!r.ok)throw new Error(data.error||'Closure could not be confirmed.');if(verify){window.location.assign(data.url);return;}if(data.accepted!==true)throw new Error('Closure could not be confirmed. Check status before trying again.');setProgress(data);onAccepted();}catch(e){setError(e instanceof Error?e.message:'Closure could not be confirmed. Try again.');}finally{setBusy(false);}}
 if(!signedIn&&!progress?.accepted)return null;
 return <section className="account-security" aria-labelledby="account-closure-title"><h2 id="account-closure-title">{progress?.accepted?'Account closed':'Close your account'}</h2>{progress?.accepted?<><p>Your account is closed and all sessions have ended. Published links, pages and files are unavailable. Signing in with this Google account cannot reopen it.</p><p role="status">{progress.complete?'Cleanup of your owned content in active storage is complete.':'Content cleanup is pending. The service retries cleanup hourly. Uncertain uploads or storage failures can delay completion; access stays blocked.'}</p><p>This does not remove provider backups, copies you or others saved, search caches or Stripe financial records. Minimal security and billing records remain.</p><button onClick={status} disabled={busy}>{busy?'Checking…':'Check cleanup status'}</button><p>This browser can check progress for 30 days. Keep this browser cookie to retain access to the status receipt.</p></>:<><p>Closing is permanent. Your private cloud designs, hosted pages and uploaded files, received form submissions and scan counts will be removed from active storage. Published links and pages stop working as soon as closure is accepted. Download any data you want to keep first.</p><p>Local copies on your devices, downloaded copies, provider backups, search caches and Stripe financial records are not removed by this action. Minimal security and billing records remain. <Link href="/billing">Check Billing</Link>: all subscriptions must have ended and checkouts must be resolved before closure can be accepted.</p>{confirm||progress?.ready?<div role="group" aria-label="Confirm permanent account closure"><p><strong>Close this account and lose access to its cloud content permanently?</strong> You cannot create a new account with this Google identity after closure.</p>{progress?.ready?<><p>Your same-account Google verification is ready for a short time. Confirm below to submit closure.</p><button onClick={()=>action(false)} disabled={busy}>{busy?'Confirming…':'Permanently close my account'}</button></>:<button onClick={()=>action(true)} disabled={busy}>{busy?'Opening Google…':'Verify with Google to continue'}</button>}<button onClick={()=>{setConfirm(false);setProgress(p=>p?{...p,ready:false}:p);}} disabled={busy}>Cancel</button></div>:<button onClick={()=>setConfirm(true)} disabled={busy}>Review account closure</button>}<button onClick={status} disabled={busy}>Check request status</button></>}{error&&<p className="account-error" role="alert">{error}</p>}</section>;
}
