'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {ArrowUpRight,CreditCard,ShieldCheck} from 'lucide-react';
import type {BillingStatus} from '@/lib/billing-types';
import {formatBillingAmount} from '@/lib/billing-format';
export default function BillingPanel(){
 const [status,setStatus]=useState<BillingStatus|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[returned,setReturned]=useState(false);
 useEffect(()=>{const controller=new AbortController();setReturned(new URLSearchParams(window.location.search).get('checkout')==='returned');fetch('/api/billing',{cache:'no-store',signal:controller.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||'Billing could not be loaded.');setStatus(data);}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Please refresh to try again.');});return()=>controller.abort();},[]);
 async function open(path:'checkout'|'portal',tier?:'pro'|'brand'){
  if(busy)return;setBusy(true);setError('');try{const response=await fetch(`/api/billing/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(tier?{tier}:{}),signal:AbortSignal.timeout(30000)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Billing could not be opened.');const url=new URL(data.url);if(url.protocol!=='https:'||!['checkout.stripe.com','billing.stripe.com'].includes(url.hostname))throw new Error('The payment page could not be verified.');window.location.assign(url.href);}catch(e){setError(e instanceof Error&&e.name!=='TimeoutError'?e.message:'Billing took too long to respond. Refresh your account before trying again.');setBusy(false);}
 }
 return <section><nav className="service-nav" aria-label="Workspace"><Link href="/designs">My designs</Link><Link href="/links">Dynamic links</Link><Link href="/content">Hosted content</Link><Link href="/account">Your account</Link><Link href="/billing" aria-current="page">Billing</Link></nav>{error&&<p role="alert" className="generator-error">{error}</p>}{!status&&!error&&<p role="status">Opening billing…</p>}
 {returned&&status&&<p className="service-notice" role="status">{status.subscription?'Your current subscription is shown below.':'Your account has been refreshed. A checkout return alone does not confirm payment; no active subscription is showing yet.'}</p>}
 {status&&!status.configured&&<div className="billing-waiting"><CreditCard size={34}/><span className="billing-label">STUDIO ACCESS</span><h2>Keep creating.</h2><p>Paid plans are not available yet. You can use the studio and its current features while billing is being connected.</p><Link href="/generator" className="primary-button">Back to your studio <ArrowUpRight size={18}/></Link></div>}
 {status?.configured&&<>{!status.signedIn&&<div className="service-gate"><ShieldCheck size={24}/><div><strong>Your plan belongs to your account.</strong><p>Sign in before choosing or managing a subscription.</p></div><Link className="nav-cta" href="/account">Sign in <ArrowUpRight size={15}/></Link></div>}{status.subscription&&<div className="billing-current"><div><span className="billing-label">YOUR SUBSCRIPTION</span><h2>{status.subscription.tier==='brand'?'Brand':'Pro'}</h2><p>{status.subscription.status.replaceAll('_',' ')}{status.subscription.cancelAtPeriodEnd?' · Scheduled to end':''}</p>{status.subscription.currentPeriodEnd&&<small>Current period ends {new Date(status.subscription.currentPeriodEnd*1000).toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'})}</small>}</div>{status.canManage&&<button className="nav-cta" disabled={busy} onClick={()=>void open('portal')}>Manage subscription <ArrowUpRight size={16}/></button>}</div>}
 {status.canManage&&!status.subscription&&<button className="nav-cta" disabled={busy} onClick={()=>void open('portal')}>Billing history and payment details <ArrowUpRight size={16}/></button>}<div className="billing-plans">{status.plans.map(plan=><article key={plan.id}><span className="billing-label">{plan.name.toUpperCase()}</span><h2>{formatBillingAmount(plan.amount,plan.currency)}<small> / {plan.intervalCount>1?`${plan.intervalCount} `:''}{plan.interval}{plan.intervalCount>1?'s':''}</small></h2><p>{plan.currency.toUpperCase()} · recurring subscription. Review the full total and applicable tax on the secure checkout page before paying.</p><button className="primary-button" disabled={busy||!status.signedIn} onClick={()=>void open(status.subscription?'portal':'checkout',plan.id)}>{busy?'Opening…':status.subscription?'Manage your plan':`Choose ${plan.name}`}<ArrowUpRight size={17}/></button></article>)}</div><p className="billing-footnote"><ShieldCheck size={15}/>Payment details are entered on Stripe’s hosted page. QR Upgrade does not receive your card number.</p></>}
 </section>;
}
