'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { Archive, Cloud, ArrowUpRight } from 'lucide-react';
import { useWorkflow } from './workflow-provider';
type RecordInfo={id:string;name:string;archived:boolean;createdAt:string;updatedAt:string};
export default function CloudLibrary(){
 const [account,setAccount]=useState<{configured:boolean;signedIn:boolean}|null>(null),[items,setItems]=useState<RecordInfo[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[query,setQuery]=useState(''),[archived,setArchived]=useState(false);
 const workflow=useWorkflow(),router=useRouter();
 useEffect(()=>{const controller=new AbortController();(async()=>{try{const response=await fetch('/api/account',{cache:'no-store',signal:controller.signal});if(!response.ok)throw new Error('Your account could not be loaded.');const status=await response.json();setAccount(status);if(status.signedIn){const r=await fetch('/api/account/designs',{cache:'no-store',signal:controller.signal});const data=await r.json();if(!r.ok)throw new Error(data.error||'Your collection could not be loaded.');setItems(data.designs);}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Please refresh to try again.');}finally{if(!controller.signal.aborted)setLoading(false);}})();return()=>controller.abort();},[]);
 async function act(item:RecordInfo,action:'open'|'archive'){
  if(busy)return;setBusy(item.id);setError('');
  try{const response=await fetch(`/api/account/designs/${item.id}`,{method:action==='open'?'GET':'PATCH',cache:'no-store',...(action==='archive'?{headers:{'Content-Type':'application/json'},body:JSON.stringify({archived:!item.archived})}:{}),signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Please try again.');if(action==='open'){workflow.setDesign({...data.design.draft,name:data.design.name,cloudId:item.id},null);router.push('/generator?resume=1');}else setItems(rows=>rows.map(row=>row.id===item.id?data.design:row));}
  catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy('');}
 }
 const visible=items.filter(item=>item.archived===archived&&item.name.toLowerCase().includes(query.trim().toLowerCase()));
 return <section className="design-library"><div className="workflow-toolbar"><Link href="/designs">On this device</Link><Link href="/account">Your account ↗</Link><Link href="/generator?new=1">New design ↗</Link></div>{error&&<p role="alert" className="generator-error">{error}</p>}{loading?<p role="status">Opening your private collection…</p>:!account?.signedIn?<div className="workflow-empty"><Cloud size={36}/><h2>{account?.configured?'Your designs, wherever you create.':'Your cloud collection is on its way.'}</h2><p>{account?.configured?'Sign in with Google to save and reopen your private designs.':'Google sign-in is being connected. Your local collection works now.'}</p><Link href="/account" className="primary-button">{account?.configured?'Sign in':'Account status'} <ArrowUpRight size={18}/></Link></div>:<><p className="workflow-disclosure">Private to your account. Up to 50 designs, including archived copies. Opening a design runs fresh scan checks. Cloud saving does not publish your QR or create a public link.</p><div className="workflow-toolbar"><label className="workflow-search"><input aria-label="Search cloud designs" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a cloud design…"/></label><button aria-pressed={archived} onClick={()=>setArchived(value=>!value)}><Archive size={16}/>{archived?'Show active':'Archive'}</button></div>{!visible.length?<div className="workflow-empty"><Cloud size={36}/><h2>{query?'No matching designs':archived?'Your archive is empty':'A home for your next idea.'}</h2><p>Choose Save to cloud in the studio to add a design.</p></div>:<div className="cloud-design-list">{visible.map(item=><article key={item.id} aria-label={item.name}><Cloud size={23}/><div><h2>{item.name}</h2><p>Saved {new Date(item.updatedAt).toLocaleDateString()}</p></div><button className="workflow-wide" disabled={!!busy} onClick={()=>void act(item,'open')}>Open in studio ↗</button><button className="workflow-wide" disabled={!!busy} onClick={()=>void act(item,'archive')}>{item.archived?'Restore':'Archive'}</button></article>)}</div>}</>}</section>;
}
