'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowDown,ArrowUp,ArrowUpRight,Archive,Copy,FileText,Image as ImageIcon,Link2,MessageSquare,Plus,QrCode,Radio,Trash2,Upload,Utensils} from 'lucide-react';
import type {ContentDraft,ContentKind,ContentPage} from '@/lib/content-types';
import {readLocalImage} from '@/lib/browser-qr';
import {newDesign} from '@/lib/new-design';
import {useWorkflow} from './workflow-provider';
import {blankContent as blank,contentDirty} from '@/lib/service-drafts';
import {useDiscardDialog} from './discard-dialog';
import {useServiceOperations} from './use-service-operations';
import HostedPageView from './hosted-page-view';

const types=[{id:'links',name:'Link page',description:'One place for every next step.',icon:Link2},{id:'menu',name:'Menu',description:'A menu that moves with you.',icon:Utensils},{id:'gallery',name:'Gallery',description:'Let the pictures tell it.',icon:ImageIcon},{id:'document',name:'Document',description:'A PDF, a scan away.',icon:FileText},{id:'form',name:'Feedback',description:'Make space for a response.',icon:MessageSquare}] as const;
type Submission={id:string;name:string;email:string;message:string;createdAt:string};
type Asset={id:string;name:string;mime:string;size:number};
async function request(path:string,method='GET',body?:unknown,signal?:AbortSignal){const response=await fetch(path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store',signal:signal?AbortSignal.any([signal,AbortSignal.timeout(20000)]):AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok)throw new Error(data.error||'This action could not be completed.');return data;}

export default function ContentWorkspace(){
 const workflow=useWorkflow(),discard=useDiscardDialog();
 const operations=useServiceOperations(workflow.epochs),loadOperations=useServiceOperations(workflow.epochs);
 const {selected,draft}=workflow.contentEditor;
 const setDraft=(update:ContentDraft|((previous:ContentDraft)=>ContentDraft))=>workflow.setContentEditor(previous=>({...previous,draft:typeof update==='function'?update(previous.draft):update}));
 const [account,setAccount]=useState<{configured:boolean;signedIn:boolean}|null>(null),[pages,setPages]=useState<ContentPage[]>([]),[assets,setAssets]=useState<Asset[]>([]),[archived,setArchived]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[preview,setPreview]=useState(false),[submissions,setSubmissions]=useState<Submission[]>([]),[inboxTotal,setInboxTotal]=useState<number|null>(null);
 const input=useRef<HTMLInputElement>(null),uploadItem=useRef<number|null>(null),router=useRouter();
 const current=pages.find(page=>page.id===selected),dirty=contentDirty(workflow.contentEditor);
 useEffect(()=>{const operation=loadOperations.begin(workflow.epochs,'account');(async()=>{try{const status=await request('/api/account','GET',undefined,operation.signal);if(!operation.current())return;setAccount(status);workflow.reconcileAccount(status.signedIn?status.user.email:null);operation.recapture();if(status.signedIn){const [collection,files]=await Promise.all([request('/api/content','GET',undefined,operation.signal),request('/api/content/assets','GET',undefined,operation.signal)]);if(operation.current()){setPages(collection.pages);setAssets(files.assets);}}}catch(e){if(operation.current())setError(e instanceof Error?e.message:'Please refresh to try again.');}finally{if(operation.alive())setLoading(false);}})();},[]);
 function choose(page?:ContentPage,kind:ContentKind='links'){discard.request(dirty,()=>{workflow.setContentEditor({selected:page?.id??null,draft:page?.draft??blank(kind),baseline:page?.draft??blank(kind)});setNotice('');setError('');setSubmissions([]);setInboxTotal(null);});}
 function change<K extends keyof ContentDraft>(key:K,value:ContentDraft[K]){setDraft(previous=>({...previous,[key]:value}));}
 function itemChange(index:number,key:keyof ContentDraft['items'][number],value:string){setDraft(previous=>({...previous,items:previous.items.map((item,i)=>i===index?{...item,[key]:value}:item)}));}
 function move(index:number,direction:number){setDraft(previous=>{const items=[...previous.items];[items[index],items[index+direction]]=[items[index+direction],items[index]];return {...previous,items};});}
 async function save(action?:'publish'|'pause'|'archive'|'restore'){
  if(busy||!account?.signedIn||action&&!current)return;const operation=operations.begin(workflow.epochs,'content');setBusy(true);setError('');setNotice('');
  try{const data=await request(`/api/content${selected?`/${selected}`:''}`,action?'PATCH':selected?'PUT':'POST',action?{action}:draft,operation.signal);if(!operation.current())return;const saved:ContentPage=data.page;setPages(rows=>[saved,...rows.filter(row=>row.id!==saved.id)]);workflow.setContentEditor({selected:saved.id,draft:saved.draft,baseline:saved.draft});setNotice(action==='publish'?'Published. This version is now available at your QR address.':action==='pause'?'Page paused. Its public address and files are unavailable.':action==='archive'?'Page archived and removed from public view.':action==='restore'?saved.status==='published'?'Page restored and public again. Its published version is available.':'Page restored. Publish it when ready to share.':'Draft saved. Publish when you are ready to share these changes.');}catch(e){if(operation.current())setError(e instanceof Error&&e.name!=='TimeoutError'?e.message:'The request timed out. Refresh your collection before trying again.');}finally{if(operation.alive())setBusy(false);}
 }
 async function upload(file?:File){if(!file||busy||!account?.signedIn)return;const operation=operations.begin(workflow.epochs,'content');setBusy(true);setError('');const index=uploadItem.current;
  try{let mime=file.type,data:string;if(draft.kind==='document'){if(mime!=='application/pdf'||file.size>2*1024*1024)throw new Error('Choose a PDF smaller than 2 MB.');data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('The file could not be read.'));reader.onabort=()=>reject(new DOMException('Upload canceled.','AbortError'));const abort=()=>reader.abort();operation.signal.addEventListener('abort',abort,{once:true});reader.onloadend=()=>operation.signal.removeEventListener('abort',abort);reader.readAsDataURL(file);});}else{const image=await readLocalImage(file);if(!operation.current())return;mime='image/png';data=image.split(',')[1];if(data.length*3/4>2*1024*1024)throw new Error('This image is too large after processing. Choose a smaller image.');}if(!operation.current())return;const result=await request('/api/content/assets','POST',{name:file.name.slice(0,120),mime,data},operation.signal);if(!operation.current())return;setAssets(rows=>[result.asset,...rows]);if(index===null)change('fileId',result.asset.id);else itemChange(index,'assetId',result.asset.id);setNotice('File uploaded privately. Save and publish your page to share it.');}catch(e){if(operation.current())setError(e instanceof Error?e.message:'Upload failed.');}finally{if(operation.alive()){setBusy(false);if(input.current)input.current.value='';}}
 }
 function pickUpload(index:number|null){uploadItem.current=index;input.current?.click();}
 async function inbox(){if(!current||busy)return;const operation=operations.begin(workflow.epochs,'content');setBusy(true);setError('');try{const result=await request(`/api/content/${current.id}/submissions`,'GET',undefined,operation.signal);if(!operation.current())return;setSubmissions(result.submissions);setInboxTotal(result.total);}catch(e){if(operation.current())setError(e instanceof Error?e.message:'Could not open messages.');}finally{if(operation.alive())setBusy(false);}}
 async function copy(){if(!current)return;try{await navigator.clipboard.writeText(current.url);setNotice('Page link copied.');}catch{setNotice('Select and copy the page address below.');}}
 function makeQr(){if(!current||current.status!=='published'||current.archived||dirty||current.hasUnpublishedChanges)return;workflow.setDesign(newDesign(current.url,draft.title),null);router.push('/generator?resume=1');}
 if(loading)return <section><p role="status">Opening your pages…</p></section>;
 return <section>{discard.dialog}<nav className="service-nav" aria-label="Workspace"><Link href="/designs">My designs</Link><Link href="/links">Dynamic links</Link><Link href="/content" aria-current="page">Hosted content</Link><Link href="/account">Your account ↗</Link></nav>
  {!loading&&!account?.signedIn&&<div className="service-gate"><FileText size={24}/><div><strong>{account?.configured?'Your next page starts here.':'Google sign-in is being connected.'}</strong><p>Explore the builders and preview your page. Sign in to save, upload and publish.</p></div><Link className="nav-cta" href="/account">{account?.configured?'Sign in':'Account status'} <ArrowUpRight size={15}/></Link></div>}
  {error&&<p className="generator-error" role="alert">{error}</p>}{notice&&<p className="service-notice" role="status">{notice}</p>}
  <div className="content-kinds" role="group" aria-label="Create a page">{types.map(type=><button key={type.id} disabled={busy} aria-pressed={draft.kind===type.id} onClick={()=>choose(undefined,type.id)}><type.icon size={23}/><strong>{type.name}</strong><span>{type.description}</span></button>)}</div>
  <div className="service-workspace content-workspace"><aside className="service-list"><div className="service-section-head"><h2>Your pages</h2><button disabled={busy} className="small-control" aria-label="New page" onClick={()=>choose()}><Plus size={17}/></button></div><button className="small-control service-archive" disabled={busy} aria-pressed={archived} onClick={()=>setArchived(!archived)}><Archive size={13}/>{archived?'Show active':'Show archive'}</button>{loading?<p role="status">Opening your pages…</p>:pages.filter(page=>page.archived===archived).length?pages.filter(page=>page.archived===archived).map(page=><button className={`service-list-item ${page.id===selected?'selected':''}`} key={page.id} disabled={busy} onClick={()=>choose(page)}><span className={`service-dot ${page.status}`}/><span><strong>{page.draft.title}</strong><small>{page.draft.kind} · {page.status}{page.hasUnpublishedChanges?' · draft changes':''}</small></span><ArrowUpRight size={14}/></button>):<div className="service-empty"><FileText size={28}/><strong>{archived?'Nothing archived.':'A blank page. A fresh possibility.'}</strong><p>Choose a format above, make it yours, then connect it to a QR.</p></div>}</aside>
  <div className="service-editor"><div className="service-section-head"><span className="section-kicker">{current?'YOUR PAGE':'MAKE SOMETHING WORTH SCANNING'}</span><button className="small-control" aria-pressed={preview} onClick={()=>setPreview(!preview)}>{preview?'Edit page':'Preview page'} <ArrowUpRight size={14}/></button></div>
  {preview?<div className="content-preview-shell"><span className="section-kicker">PRIVATE PREVIEW · LINKS AND FORMS INACTIVE</span><HostedPageView content={draft} preview/></div>:<><h2>{types.find(type=>type.id===draft.kind)?.name}</h2><p className="service-intro">Build your page here. Your draft stays private until you publish.</p><fieldset className="content-fields" disabled={busy}><label className="generator-field">Page title<input maxLength={80} value={draft.title} onChange={e=>change('title',e.target.value)} placeholder="Something worth discovering"/></label><label className="generator-field">Introduction<textarea rows={3} maxLength={1000} value={draft.description} onChange={e=>change('description',e.target.value)} placeholder="Set the scene in a sentence or two."/></label><label className="content-accent">Backlight colour<input type="color" value={draft.accent} onChange={e=>change('accent',e.target.value)}/><code>{draft.accent}</code></label>
  {['links','menu','gallery'].includes(draft.kind)&&<section className="content-items"><div className="service-section-head"><h3>{draft.kind==='menu'?'The menu':draft.kind==='gallery'?'Your images':'Your links'}</h3><span>{draft.items.length}/12</span></div>{draft.items.map((item,index)=><fieldset className="content-item" key={index}><legend>{String(index+1).padStart(2,'0')}</legend><div className="content-item-tools"><button type="button" className="small-control" aria-label={`Move item ${index+1} up`} disabled={index===0} onClick={()=>move(index,-1)}><ArrowUp size={13}/></button><button type="button" className="small-control" aria-label={`Move item ${index+1} down`} disabled={index===draft.items.length-1} onClick={()=>move(index,1)}><ArrowDown size={13}/></button><button type="button" className="small-control" aria-label={`Remove item ${index+1}`} onClick={()=>change('items',draft.items.filter((_,i)=>i!==index))}><Trash2 size={13}/></button></div><label className="generator-field">{draft.kind==='menu'?'Item name':draft.kind==='gallery'?'Image title':'Link title'}<input maxLength={80} value={item.title} onChange={e=>itemChange(index,'title',e.target.value)}/></label><label className="generator-field">{draft.kind==='gallery'?'Image description (also used as alt text)':'Description (optional)'}<textarea rows={2} maxLength={300} value={item.description} onChange={e=>itemChange(index,'description',e.target.value)}/></label>{draft.kind==='menu'&&<label className="generator-field">Price (include your currency)<input maxLength={30} value={item.price} placeholder="$18 AUD" onChange={e=>itemChange(index,'price',e.target.value)}/></label>}{draft.kind!=='gallery'?<label className="generator-field">{draft.kind==='links'?'Destination URL':'More information URL (optional)'}<input type="url" maxLength={2048} value={item.url} placeholder="https://" onChange={e=>itemChange(index,'url',e.target.value)}/></label>:<><label className="generator-field">Image<select value={item.assetId} onChange={e=>itemChange(index,'assetId',e.target.value)}><option value="">Choose an uploaded image</option>{assets.filter(asset=>asset.mime.startsWith('image/')).map(asset=><option value={asset.id} key={asset.id}>{asset.name}</option>)}</select></label><button className="workflow-wide" disabled={!account?.signedIn} onClick={()=>pickUpload(index)}><Upload size={15}/>Upload image</button>{item.assetId&&<img className="content-image-thumb" src={`/api/content/assets/${item.assetId}`} alt={item.description||item.title}/>}</>}</fieldset>)}<button type="button" className="workflow-wide" disabled={draft.items.length>=12} onClick={()=>change('items',[...draft.items,{title:'',description:'',price:'',url:'',assetId:''}])}><Plus size={16}/>Add {draft.kind==='menu'?'menu item':draft.kind==='gallery'?'image':'link'}</button></section>}
  {draft.kind==='document'&&<div className="content-file"><FileText size={30}/><h3>A document, beautifully connected.</h3><p>Upload a PDF up to 2 MB. Visitors download the file from your published page.</p><label className="generator-field">Document<select value={draft.fileId} onChange={e=>change('fileId',e.target.value)}><option value="">Choose an uploaded PDF</option>{assets.filter(asset=>asset.mime==='application/pdf').map(asset=><option value={asset.id} key={asset.id}>{asset.name}</option>)}</select></label><button className="workflow-wide" disabled={!account?.signedIn} onClick={()=>pickUpload(null)}><Upload size={15}/>Upload PDF</button></div>}
  {draft.kind==='form'&&<div className="content-file"><MessageSquare size={29}/><h3>A simple way to hear back.</h3><p>Your form asks for a message, optional name and email, and consent. Responses appear in your private inbox here.</p><label className="generator-field">Thank-you message<textarea rows={3} maxLength={300} value={draft.formMessage} onChange={e=>change('formMessage',e.target.value)}/></label><p className="generator-note">Responses stay in your account. This form is for ordinary feedback; do not request sensitive personal information.</p></div>}
  </fieldset><input hidden ref={input} type="file" accept={draft.kind==='document'?'application/pdf':'image/png,image/jpeg,image/webp'} onChange={e=>void upload(e.target.files?.[0])}/></>}
  <div className="content-save-row"><button className="primary-button" disabled={busy||!account?.signedIn||!draft.title.trim()} onClick={()=>void save()}>{busy?'Working…':current?'Save draft changes':'Save draft'}<ArrowUpRight size={17}/></button>{dirty&&<span>Unsaved changes</span>}</div>
  {current&&<><div className="service-address"><span className="section-kicker">YOUR PAGE ADDRESS · {current.archived?'ARCHIVED':current.status.toUpperCase()}</span><code>{current.url}</code>{current.hasUnpublishedChanges&&<p>You have saved changes that are not published yet. Publish them before designing its QR.</p>}<div className="workflow-card-actions"><button disabled={busy} onClick={()=>void copy()}><Copy size={14}/>Copy link</button>{current.status==='published'&&!current.archived&&<a href={current.url} target="_blank" rel="noreferrer">Open published page ↗</a>}</div></div><div className="service-actions"><button className="workflow-wide" disabled={busy||dirty||current.archived} onClick={()=>void save('publish')}><Radio size={16}/>{current.status==='published'?'Publish latest draft':'Publish page'}</button><button className="workflow-wide" disabled={busy||dirty||current.status!=='published'||current.archived||current.hasUnpublishedChanges} onClick={makeQr}><QrCode size={16}/>Design its QR</button>{current.status==='published'&&!current.archived&&<button className="small-control" disabled={busy||dirty} onClick={()=>void save('pause')}>Pause page</button>}<button className="small-control" disabled={busy||dirty} onClick={()=>void save(current.archived?'restore':'archive')}>{current.archived?(current.status==='published'?'Restore and reactivate page':'Restore page'):'Archive page'}</button></div>{dirty&&<p className="generator-note">Save your draft before publishing or making its QR.</p>}{current.draft.kind==='form'&&<section className="content-inbox"><div className="service-section-head"><h3>Your private inbox</h3><button className="small-control" disabled={busy} onClick={()=>void inbox()}>{inboxTotal===null?'Open messages':'Refresh messages'}</button></div>{inboxTotal!==null&&<p>{inboxTotal} responses · showing the latest {submissions.length}</p>}{submissions.map(message=><article key={message.id}><strong>{message.name||'Anonymous'}</strong><time dateTime={message.createdAt}>{new Date(message.createdAt).toLocaleString()}</time>{message.email&&<span>{message.email}</span>}<p>{message.message}</p></article>)}</section>}</>}
  </div></div>
 </section>;
}
