'use client';
import React,{useState,type CSSProperties} from 'react';
import {ArrowUpRight,FileDown,Send} from 'lucide-react';
import type {ContentDraft} from '@/lib/content-types';

/** The same safe, structured renderer is used for the editor preview and public page. */
export default function HostedPageView({content,slug,preview=false}:{content:ContentDraft;slug?:string;preview?:boolean}){
 const asset=(id:string)=>preview?`/api/content/assets/${id}`:`/p/${slug}/assets/${id}`;
 const [busy,setBusy]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState('');
 async function submit(event:React.FormEvent<HTMLFormElement>){
  event.preventDefault();if(preview||!slug||busy)return;const form=event.currentTarget,values=new FormData(form);setBusy(true);setError('');
  try{const response=await fetch(`/api/content/public/${slug}/submissions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:values.get('name')||'',email:values.get('email')||'',message:values.get('message')||'',consent:values.get('consent')==='on',website:values.get('website')||''}),signal:AbortSignal.timeout(15000)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Your message could not be sent.');setSent(true);form.reset();}catch(e){setError(e instanceof Error&&e.name!=='TimeoutError'?e.message:'Please try again in a moment.');}finally{setBusy(false);}
 }
 return <article className={`hosted-page ${preview?'hosted-preview':''}`} style={{'--page-accent':content.accent} as CSSProperties}>
  <div className="hosted-light" aria-hidden="true"/><header><span className="hosted-category">{content.kind==='links'?'THE NEXT CONNECTION':content.kind==='menu'?'ON THE MENU':content.kind==='gallery'?'IN THE FRAME':content.kind==='document'?'YOURS TO KEEP':'LET’S HEAR IT'}</span><h1>{content.title||'Your page. Your story.'}</h1>{content.description&&<p>{content.description}</p>}</header>
  {content.kind==='links'&&<div className="hosted-links">{content.items.map((item,index)=>preview?<div className="hosted-link" key={index}><span><strong>{item.title||'Link title'}</strong>{item.description&&<small>{item.description}</small>}</span><ArrowUpRight size={20}/></div>:<a className="hosted-link" key={index} href={item.url} rel="noreferrer"><span><strong>{item.title}</strong>{item.description&&<small>{item.description}</small>}</span><ArrowUpRight size={20}/></a>)}</div>}
  {content.kind==='menu'&&<div className="hosted-menu">{content.items.map((item,index)=><section key={index}><div><h2>{item.title||'A signature dish'}</h2>{item.description&&<p>{item.description}</p>}{item.url&&!preview&&<a href={item.url} rel="noreferrer">Find out more <ArrowUpRight size={13}/></a>}</div><strong>{item.price}</strong></section>)}</div>}
  {content.kind==='gallery'&&<div className="hosted-gallery">{content.items.map((item,index)=><figure key={index}>{item.assetId?<img src={asset(item.assetId)} alt={item.description||item.title} loading="lazy"/>:<div className="hosted-image-placeholder">Your image here</div>}<figcaption><strong>{item.title}</strong>{item.description&&<span>{item.description}</span>}</figcaption></figure>)}</div>}
  {content.kind==='document'&&(content.fileId&&!preview?<a className="hosted-document" href={asset(content.fileId)} download><FileDown size={30}/><span><strong>Download the document</strong><small>PDF · opens as a file download</small></span><ArrowUpRight size={20}/></a>:<div className="hosted-document"><FileDown size={30}/><span><strong>{content.fileId?'Your document is attached':'Attach your document'}</strong><small>PDF download</small></span></div>)}
  {content.kind==='form'&&(sent?<div className="hosted-thanks" role="status"><Send size={24}/><h2>Message delivered.</h2><p>{content.formMessage||'Thank you for taking a moment to share.'}</p></div>:<form className="hosted-form" onSubmit={submit}><label>Name <span>optional</span><input name="name" maxLength={80} autoComplete="name" disabled={busy||preview}/></label><label>Email <span>optional</span><input name="email" type="email" maxLength={254} autoComplete="email" disabled={busy||preview}/></label><label>Your message<textarea name="message" required maxLength={2000} rows={5} disabled={busy||preview}/></label><label className="hosted-honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="hosted-consent"><input name="consent" type="checkbox" required disabled={busy||preview}/><span>I agree to share this message and any contact details I enter with the owner of this page.</span></label><p className="hosted-privacy">Please do not include passwords, payment details, or sensitive personal information. Your message is stored privately for the page owner.</p>{error&&<p role="alert" className="generator-error">{error}</p>}<button className="primary-button" disabled={busy||preview} type="submit">{preview?'Form preview':busy?'Sending…':'Send message'}<Send size={16}/></button></form>)}
  <footer>MADE WITH {preview?<span><img src="/brand/qr-upgrade-logo-v3-64.png" alt=""/>QR Upgrade</span>:<a href="https://qrupgrade.com"><img src="/brand/qr-upgrade-logo-v3-64.png" alt=""/>QR Upgrade</a>}</footer>
 </article>;
}
