'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowUpRight, Copy, Link2, Plus, QrCode, Radio, Pause, Archive, BarChart3, ExternalLink } from 'lucide-react';
import { useWorkflow } from './workflow-provider';
import {linkDirty} from '@/lib/service-drafts';
import {useDiscardDialog} from './discard-dialog';
import { newDesign } from '@/lib/new-design';
type DynamicLink={id:string;slug:string;name:string;target:string;status:'draft'|'published'|'paused';archived:boolean;url:string;createdAt:string;updatedAt:string;analytics:{totalOpens:number;opensLast30Days:number;daily:{day:string;count:number}[]}};
type AccountStatus={configured:boolean;signedIn:boolean};
export default function LinkWorkspace(){
 const workflow=useWorkflow(),discard=useDiscardDialog(),router=useRouter();
 const {selected,name,target}=workflow.linkEditor;
 const setName=(name:string)=>workflow.setLinkEditor(previous=>({...previous,name}));
 const setTarget=(target:string)=>workflow.setLinkEditor(previous=>({...previous,target}));
 const [account,setAccount]=useState<AccountStatus|null>(null),[links,setLinks]=useState<DynamicLink[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[archived,setArchived]=useState(false);
 const current=links.find(link=>link.id===selected);const isDirty=linkDirty(workflow.linkEditor);
 useEffect(()=>{const controller=new AbortController();(async()=>{try{const r=await fetch('/api/account',{cache:'no-store',signal:controller.signal});if(!r.ok)throw new Error('Your account could not be loaded.');const status=await r.json();setAccount(status);workflow.reconcileAccount(status.signedIn?status.user.email:null);if(status.signedIn){const response=await fetch('/api/links',{cache:'no-store',signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.error);setLinks(data.links);}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Please refresh to try again.');}finally{if(!controller.signal.aborted)setLoading(false);}})();return()=>controller.abort();},[]);
 function replace(link?:DynamicLink){workflow.setLinkEditor({selected:link?.id??null,name:link?.name??'',target:link?.target??'',baseline:{name:link?.name??'',target:link?.target??''}});setError('');setNotice('');}
 function choose(link?:DynamicLink){discard.request(isDirty,()=>replace(link));}
 async function update(change?:{status?:DynamicLink['status'];archived?:boolean}){
  if(busy||!account?.signedIn)return;setBusy(true);setError('');setNotice('');
  try{const response=await fetch(`/api/links${selected?`/${selected}`:''}`,{method:selected?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(change||{name:name.trim(),target:target.trim()}),signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not save this link.');const saved:DynamicLink=data.link;setLinks(rows=>[saved,...rows.filter(row=>row.id!==saved.id)]);replace(saved);setNotice(change?.status==='published'?'Published. Your QR link is ready to use.':change?.status==='paused'?'Paused. The QR link no longer redirects.':change?.archived?'Archived. The public link is unavailable.':selected?'Changes saved. Your QR address stays the same.':'Draft saved. Publish it when you are ready.');}
  catch(e){setError(e instanceof Error&&e.name!=='TimeoutError'?e.message:'The request timed out. Refresh your collection before trying again.');}finally{setBusy(false);}
 }
 function createQr(){if(!current||current.status!=='published'||current.archived||isDirty)return;workflow.setDesign(newDesign(current.url,current.name),null);router.push('/generator?resume=1');}
 async function copy(){if(!current)return;try{await navigator.clipboard.writeText(current.url);setNotice('QR link copied.');}catch{setNotice('Select and copy the QR link below.');}}
 const active=links.filter(link=>!link.archived),visible=links.filter(link=>link.archived===archived),daily=current?.analytics.daily??[],highest=Math.max(1,...daily.map(day=>day.count));
 if(loading)return <section><p role="status">Opening your links…</p></section>;
 return <section>{discard.dialog}<nav className="service-nav" aria-label="Workspace"><Link href="/designs">My designs</Link><Link href="/links" aria-current="page">Dynamic links</Link><Link href="/content">Hosted content</Link><Link href="/account">Your account ↗</Link></nav>
 {!loading&&!account?.signedIn&&<div className="service-gate"><Link2 size={24}/><div><strong>{account?.configured?'Sign in to keep your links connected.':'Google sign-in is being connected.'}</strong><p>{account?.configured?'Your links and aggregate scan counts belong to your account.':'You can explore the builder. Publishing becomes available when account setup is complete.'}</p></div><Link className="nav-cta" href="/account">{account?.configured?'Sign in':'Account status'} <ArrowUpRight size={15}/></Link></div>}
 {error&&<p className="generator-error" role="alert">{error}</p>}{notice&&<p className="service-notice" role="status">{notice}</p>}
 <div className="service-stats"><div><Link2 size={18}/><strong>{account?.signedIn?active.length:"—"}</strong><span>Active links</span></div><div><Radio size={18}/><strong>{account?.signedIn?active.filter(link=>link.status==='published').length:"—"}</strong><span>Published links</span></div><div><BarChart3 size={18}/><strong>{account?.signedIn?links.reduce((sum,link)=>sum+link.analytics.opensLast30Days,0).toLocaleString():"—"}</strong><span>Opens · last 30 days</span></div></div>
 <div className="service-workspace"><aside className="service-list"><div className="service-section-head"><h2>Your links</h2><button className="small-control" disabled={busy} onClick={()=>choose()} aria-label="New dynamic link"><Plus size={17}/></button></div><button className="small-control service-archive" disabled={busy} aria-pressed={archived} onClick={()=>setArchived(value=>!value)}><Archive size={13}/>{archived?'Show active':'Show archive'}</button>{loading?<p role="status">Opening your collection…</p>:visible.length?visible.map(link=><button disabled={busy} key={link.id} className={`service-list-item ${link.id===selected?'selected':''}`} onClick={()=>choose(link)}><span className={`service-dot ${link.status}`}/><span><strong>{link.name}</strong><small>{link.status} · {link.analytics.totalOpens} opens</small></span><ArrowUpRight size={15}/></button>):<div className="service-empty"><Link2 size={28}/><strong>{archived?'Nothing archived.':'Your first link starts here.'}</strong><p>Give it a name, choose a destination, and publish when it is ready.</p></div>}</aside>
 <div className="service-editor"><span className="section-kicker">{current?'EDIT DESTINATION':'A NEW CONNECTION'}</span><h2>{current?current.name:'Where should it lead?'}</h2><p className="service-intro">Your permanent QR address stays the same when you update its destination.</p><form onSubmit={e=>{e.preventDefault();void update();}}><label className="generator-field">Link name<input required maxLength={80} value={name} disabled={busy} onChange={e=>setName(e.target.value)} placeholder="Spring collection"/></label><label className="generator-field">Destination URL<input required type="url" maxLength={2048} value={target} disabled={busy} onChange={e=>setTarget(e.target.value)} placeholder="https://your-website.com/collection"/></label><p className="generator-note">Use a public HTTPS address. A draft does not redirect until you publish it.</p><button className="primary-button" disabled={busy||!account?.signedIn||!name.trim()||!target.trim()} type="submit">{busy?'Saving…':current?'Save destination':'Save draft'} <ArrowUpRight size={17}/></button></form>
 {current&&<><div className="service-address"><span className="section-kicker">YOUR QR ADDRESS · {current.archived?'ARCHIVED':current.status.toUpperCase()}</span><code>{current.url}</code><p>Opens {current.target}</p><div className="workflow-card-actions"><button disabled={busy} onClick={()=>void copy()}><Copy size={14}/>Copy link</button>{current.status==='published'&&!current.archived&&<a href={current.url} target="_blank" rel="noreferrer">Test link <ExternalLink size={14}/></a>}</div></div><div className="service-actions"><button className="workflow-wide" disabled={busy||current.archived||isDirty} onClick={()=>void update({status:current.status==='published'?'paused':'published'})}>{current.status==='published'?<Pause size={16}/>:<Radio size={16}/>} {current.status==='published'?'Pause link':'Publish link'}</button><button className="workflow-wide" disabled={busy||current.status!=='published'||current.archived||isDirty} onClick={createQr}><QrCode size={16}/>Design its QR</button><button className="small-control" disabled={busy||isDirty} onClick={()=>void update({archived:!current.archived})}>{current.archived?(current.status==='published'?'Restore and reactivate link':'Restore link'):'Archive'}</button></div>{isDirty&&<p className="generator-note">Save your destination changes before publishing or making a QR.</p>}<section className="service-analytics"><div className="service-section-head"><h3>Every opening is a connection.</h3><strong>{current.analytics.totalOpens.toLocaleString()} total</strong></div><p>Daily opens for the last 30 days. Counts include repeat visits and bots; they are not unique people. No IP addresses or visitor profiles are stored.</p><div className="service-bars" role="img" aria-label={`${current.analytics.opensLast30Days} opens over the last 30 days`}>{daily.map(day=><span key={day.day} style={{height:`${Math.max(2,day.count/highest*100)}%`}} title={`${day.day}: ${day.count}`}/>)}</div><details><summary>View daily counts</summary><table><thead><tr><th>Date (UTC)</th><th>Opens</th></tr></thead><tbody>{daily.map(day=><tr key={day.day}><td>{day.day}</td><td>{day.count}</td></tr>)}</tbody></table></details></section></>}
 </div></div></section>;
}
